# Generated by Django 4.2.6 on 2023-10-30 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_useraccount_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='phone_number',
        ),
    ]
