# Generated by Django 4.2.6 on 2023-10-30 12:43

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_useraccount_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='full_name',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='username',
            field=models.CharField(default=1, max_length=40, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[(1, 'Admin'), (2, 'Student'), (3, 'Teacher')], default='STUDENT', max_length=20),
        ),
    ]
