# Generated by Django 4.2.6 on 2023-11-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_teacherprofile_studentprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='specilization',
            new_name='specialization',
        ),
        migrations.AddField(
            model_name='course',
            name='about',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
