# Generated by Django 4.2.6 on 2023-11-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_specilization_studentprofile_specialization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='about',
            field=models.TextField(max_length=1000),
        ),
    ]
