# Generated by Django 4.2.6 on 2023-11-29 09:19

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_studentprofile_country_alter_studentprofile_pin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherprofile',
            old_name='experience',
            new_name='comapany_name',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='Job_role',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.upload_to),
        ),
    ]
