# Generated by Django 4.2.6 on 2023-11-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_rename_comapany_name_teacherprofile_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='about',
            field=models.CharField(max_length=500),
        ),
    ]
