# Generated by Django 4.2.6 on 2023-12-17 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_no', models.IntegerField()),
                ('question', models.CharField()),
                ('option_a', models.CharField()),
                ('option_b', models.CharField()),
                ('option_c', models.CharField()),
                ('option_d', models.CharField()),
                ('answer', models.CharField(choices=[('A', 'option_a'), ('B', 'option_b'), ('C', 'option_c'), ('D', 'option_d')], max_length=1)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.quiz')),
            ],
        ),
    ]
