# Generated by Django 4.2.6 on 2024-01-31 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_room_students_alter_room_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquiz',
            name='response',
            field=models.FileField(default=1, upload_to='studentquiz/'),
            preserve_default=False,
        ),
    ]
