# Generated by Django 4.2.6 on 2024-03-19 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_alter_order_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='account',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
